name: AutoRecord
on:
  workflow_dispatch:
  schedule:
    - cron: '30 00 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-python@v4
        with:
            python-version: "3.10"
      - name: Install
        run:
            pip install -r requirements.txt
      # - name: Install playwright
      #   run:
      #       playwright install
      - name: Run
        env:
            URL: ${{secrets.URL}}
        run: |
            python main.py
      - name: config git
        run: git config --global user.email "actions@gmail.com"&&git config --global user.name "Github Actions"
      - name: Push
        run: git status&&git add .&&git commit -m "update by github actions"&&git push origin main
